### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by kairusds** [kairusds/eidolonrp#2]
Add a config file and instructions for setting up the bot

**Comment by Forgiving0** [comment]
Your script is accurate and working.... 10/10. I'm currently hosting it on repl.it

**Comment by kairusds** [comment]
> Your script is accurate and working.... 10/10. I'm currently hosting it on repl.it

im surprised you knew how to find the image id's

**Comment by kairusds** [comment]
ah fuck i forgot to do this again

**Comment by kairusds** [comment]
this should be done for now
