### ISSUE TITLE
How remove the rich-presence/How to add buttons

### ISSUE THREAD

**Issue by Tom-GARNIER** [kairusds/eidolonrp#3]
Hello, 
I started the script i disabled it but how to remove status
Second, how to add website, url type buttons
Thank you

(Your script is awesome)

**Comment by vbajs** [comment]
> I started the script i disabled it but how to remove status

May you please clarify? I may understand that English may not be your native language but I can't understand what do you mean, unless you just want buttons without any Rich Presence which AFAIK, is not possible.

> Second, how to add website, url type buttons

That, you'll have to open a new issue over at [Rapptz/discord.py](https://github.com/Rapptz/discord.py), since as I have read the discord.py docs, there's so far no implementation of rich presence buttons. (though, it might be possible that I have missed over it)

**Comment by Tom-GARNIER** [comment]
@vbajs
When I start the script on my computer, how do I remove the rich-presence? (it is important)
There are other rich-presence modules that allow button display but they don't suit me. (it does not matter)

**Comment by vbajs** [comment]
> @vbajs
> When I start the script on my computer, how do I remove the rich-presence? (it is important)
> There are other rich-presence modules that allow button display but they don't suit me. (it does not matter)

I believe it's not possible to have buttons without rich-presence, though, I may be proved wrong

**Comment by Tom-GARNIER** [comment]
@vbajs 
Ok, but how to stop the rich-presence

**Comment by kairusds** [comment]
> @vbajs
> Ok, but how to stop the rich-presence

just stop the script and the rich presence should disappear with it `CTRL+C`

**Comment by kairusds** [comment]
> > @vbajs
> > Ok, but how to stop the rich-presence
> 
> just stop the script and the rich presence should disappear with it `CTRL+C`.

as for the join/invite buttons i don't think it would be possible

**Comment by 9lag** [comment]
> > I started the script i disabled it but how to remove status
> 
> May you please clarify? I may understand that English may not be your native language but I can't understand what do you mean, unless you just want buttons without any Rich Presence which AFAIK, is not possible.
> 
> > Second, how to add website, url type buttons
> 
> That, you'll have to open a new issue over at [Rapptz/discord.py](https://github.com/Rapptz/discord.py), since as I have read the discord.py docs, there's so far no implementation of rich presence buttons. (though, it might be possible that I have missed over it)

Hello can you help me

**Comment by vbajs** [comment]
> > > I started the script i disabled it but how to remove status
> > 
> > May you please clarify? I may understand that English may not be your native language but I can't understand what do you mean, unless you just want buttons without any Rich Presence which AFAIK, is not possible.
> > 
> > > Second, how to add website, url type buttons
> > 
> > That, you'll have to open a new issue over at [Rapptz/discord.py](https://github.com/Rapptz/discord.py), since as I have read the discord.py docs, there's so far no implementation of rich presence buttons. (though, it might be possible that I have missed over it)
> 
> Hello can you help me

Hasn't kairusds said that they'll be making installation instructions?
And also, the assets problem, the method I use to extract assets ID is rather cursed and hard to explain
So I recommend you to wait for kairusds to finish documenting their installation instructions instead of plaguing every issue in this repo.

**Comment by 9lag** [comment]
> > > > I started the script i disabled it but how to remove status
> > > 
> > > 
> > > May you please clarify? I may understand that English may not be your native language but I can't understand what do you mean, unless you just want buttons without any Rich Presence which AFAIK, is not possible.
> > > > Second, how to add website, url type buttons
> > > 
> > > 
> > > That, you'll have to open a new issue over at [Rapptz/discord.py](https://github.com/Rapptz/discord.py), since as I have read the discord.py docs, there's so far no implementation of rich presence buttons. (though, it might be possible that I have missed over it)
> > 
> > 
> > Hello can you help me
> 
> Hasn't kairusds said that they'll be making installation instructions?
> And also, the assets problem, the method I use to extract assets ID is rather cursed and hard to explain
> So I recommend you to wait for kairusds to finish documenting their installation instructions instead of plaguing every issue in this repo.

no how did you do yours

**Comment by 9lag** [comment]
> > > > I started the script i disabled it but how to remove status
> > > 
> > > 
> > > May you please clarify? I may understand that English may not be your native language but I can't understand what do you mean, unless you just want buttons without any Rich Presence which AFAIK, is not possible.
> > > > Second, how to add website, url type buttons
> > > 
> > > 
> > > That, you'll have to open a new issue over at [Rapptz/discord.py](https://github.com/Rapptz/discord.py), since as I have read the discord.py docs, there's so far no implementation of rich presence buttons. (though, it might be possible that I have missed over it)
> > 
> > 
> > Hello can you help me
> 
> Hasn't kairusds said that they'll be making installation instructions?
> And also, the assets problem, the method I use to extract assets ID is rather cursed and hard to explain
> So I recommend you to wait for kairusds to finish documenting their installation instructions instead of plaguing every issue in this repo.

https://discordapp.com/api/oauth2/applications/%5Bappid%5D/assets
something like thar 
https://gist.github.com/SilverCory/99c99f2dbafb3cbdafe60edd9c9db121
