### ISSUE TITLE
Its working fine but..............

### ISSUE THREAD

**Issue by 9lag** [kairusds/eidolonrp#4]
Its working but my images will not load in 
https://media.discordapp.net/attachments/809004009079177216/813963235535093770/unknown.png
https://media.discordapp.net/attachments/809004009079177216/813962253752729600/unknown.png
each of my freinds took pics could you please help me

**Comment by 9lag** [comment]
[https://media.discordapp.net/attachments/809004009079177216/813962253752729600/unknown.png](url)

**Comment by 9lag** [comment]
![image](https://user-images.githubusercontent.com/78369995/108941312-7b9c4c00-761a-11eb-9cff-2e94935c8709.png)
![image](https://user-images.githubusercontent.com/78369995/108941320-7fc86980-761a-11eb-8d06-719ccc899483.png)

**Comment by kairusds** [comment]
im still working on a tutorial for installing it please wait

**Comment by 9lag** [comment]
> im still working on a tutorial for installing it please wait

It works fine i can make a tutriol if u need lols its easy just like i tried changing the imageid to a image id like 9727038172039817 still didnt work but am i doing soemthing wrong

**Comment by kairusds** [comment]
> > im still working on a tutorial for installing it please wait
> 
> It works fine i can make a tutriol if u need lols its easy just like i tried changing the imageid to a image id like 9727038172039817 still didnt work but am i doing soemthing wrong

did you set it with the same app id as the one where rich presence assets are added?

**Comment by 9lag** [comment]
> > > im still working on a tutorial for installing it please wait
> > 
> > 
> > It works fine i can make a tutriol if u need lols its easy just like i tried changing the imageid to a image id like 9727038172039817 still didnt work but am i doing soemthing wrong
> 
> did you set it with the same app id as the one where rich presence assets are added?

Yes

**Comment by 9lag** [comment]
do u have a discord i can add or can u add me 9lag#9999 so i can send all assets

**Comment by kairusds** [comment]
> > > > im still working on a tutorial for installing it please wait
> > > 
> > > 
> > > It works fine i can make a tutriol if u need lols its easy just like i tried changing the imageid to a image id like 9727038172039817 still didnt work but am i doing soemthing wrong
> > 
> > 
> > did you set it with the same app id as the one where rich presence assets are added?
> 
> Yes

weird, I'll try checking it later since im adding a config file support atm

**Comment by 9lag** [comment]
> > > > > im still working on a tutorial for installing it please wait
> > > > 
> > > > 
> > > > It works fine i can make a tutriol if u need lols its easy just like i tried changing the imageid to a image id like 9727038172039817 still didnt work but am i doing soemthing wrong
> > > 
> > > 
> > > did you set it with the same app id as the one where rich presence assets are added?
> > 
> > 
> > Yes
> 
> weird, I'll try checking it later since im adding a config file support atm

Do i need all the assets is that why like i didnt add small image

**Comment by kairusds** [comment]
> > > > > > im still working on a tutorial for installing it please wait
> > > > > 
> > > > > 
> > > > > It works fine i can make a tutriol if u need lols its easy just like i tried changing the imageid to a image id like 9727038172039817 still didnt work but am i doing soemthing wrong
> > > > 
> > > > 
> > > > did you set it with the same app id as the one where rich presence assets are added?
> > > 
> > > 
> > > Yes
> > 
> > 
> > weird, I'll try checking it later since im adding a config file support atm
> 
> Do i need all the assets is that why like i didnt add small image

what do you mean?

**Comment by 9lag** [comment]
> > > > > > > im still working on a tutorial for installing it please wait
> > > > > > 
> > > > > > 
> > > > > > It works fine i can make a tutriol if u need lols its easy just like i tried changing the imageid to a image id like 9727038172039817 still didnt work but am i doing soemthing wrong
> > > > > 
> > > > > 
> > > > > did you set it with the same app id as the one where rich presence assets are added?
> > > > 
> > > > 
> > > > Yes
> > > 
> > > 
> > > weird, I'll try checking it later since im adding a config file support atm
> > 
> > 
> > Do i need all the assets is that why like i didnt add small image
> 
> what do you mean?

Like i didnt add small image

**Comment by kairusds** [comment]
> > > > > > > > im still working on a tutorial for installing it please wait
> > > > > > > 
> > > > > > > 
> > > > > > > It works fine i can make a tutriol if u need lols its easy just like i tried changing the imageid to a image id like 9727038172039817 still didnt work but am i doing soemthing wrong
> > > > > > 
> > > > > > 
> > > > > > did you set it with the same app id as the one where rich presence assets are added?
> > > > > 
> > > > > 
> > > > > Yes
> > > > 
> > > > 
> > > > weird, I'll try checking it later since im adding a config file support atm
> > > 
> > > 
> > > Do i need all the assets is that why like i didnt add small image
> > 
> > 
> > what do you mean?
> 
> Like i didnt add small image

i think so

**Comment by 9lag** [comment]
> > > > > > > > > im still working on a tutorial for installing it please wait
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It works fine i can make a tutriol if u need lols its easy just like i tried changing the imageid to a image id like 9727038172039817 still didnt work but am i doing soemthing wrong
> > > > > > > 
> > > > > > > 
> > > > > > > did you set it with the same app id as the one where rich presence assets are added?
> > > > > > 
> > > > > > 
> > > > > > Yes
> > > > > 
> > > > > 
> > > > > weird, I'll try checking it later since im adding a config file support atm
> > > > 
> > > > 
> > > > Do i need all the assets is that why like i didnt add small image
> > > 
> > > 
> > > what do you mean?
> > 
> > 
> > Like i didnt add small image
> 
> i think so

Ok i tried same thing

**Comment by kairusds** [comment]
> > > > > > > > > > im still working on a tutorial for installing it please wait
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > It works fine i can make a tutriol if u need lols its easy just like i tried changing the imageid to a image id like 9727038172039817 still didnt work but am i doing soemthing wrong
> > > > > > > > 
> > > > > > > > 
> > > > > > > > did you set it with the same app id as the one where rich presence assets are added?
> > > > > > > 
> > > > > > > 
> > > > > > > Yes
> > > > > > 
> > > > > > 
> > > > > > weird, I'll try checking it later since im adding a config file support atm
> > > > > 
> > > > > 
> > > > > Do i need all the assets is that why like i didnt add small image
> > > > 
> > > > 
> > > > what do you mean?
> > > 
> > > 
> > > Like i didnt add small image
> > 
> > 
> > i think so
> 
> Ok i tried same thing

did it work?

**Comment by 9lag** [comment]
> > > > > > > > > > > im still working on a tutorial for installing it please wait
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > It works fine i can make a tutriol if u need lols its easy just like i tried changing the imageid to a image id like 9727038172039817 still didnt work but am i doing soemthing wrong
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > did you set it with the same app id as the one where rich presence assets are added?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Yes
> > > > > > > 
> > > > > > > 
> > > > > > > weird, I'll try checking it later since im adding a config file support atm
> > > > > > 
> > > > > > 
> > > > > > Do i need all the assets is that why like i didnt add small image
> > > > > 
> > > > > 
> > > > > what do you mean?
> > > > 
> > > > 
> > > > Like i didnt add small image
> > > 
> > > 
> > > i think so
> > 
> > 
> > Ok i tried same thing
> 
> did it work?

no

**Comment by 9lag** [comment]
> > > > > > > > > > > im still working on a tutorial for installing it please wait
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > It works fine i can make a tutriol if u need lols its easy just like i tried changing the imageid to a image id like 9727038172039817 still didnt work but am i doing soemthing wrong
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > did you set it with the same app id as the one where rich presence assets are added?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Yes
> > > > > > > 
> > > > > > > 
> > > > > > > weird, I'll try checking it later since im adding a config file support atm
> > > > > > 
> > > > > > 
> > > > > > Do i need all the assets is that why like i didnt add small image
> > > > > 
> > > > > 
> > > > > what do you mean?
> > > > 
> > > > 
> > > > Like i didnt add small image
> > > 
> > > 
> > > i think so
> > 
> > 
> > Ok i tried same thing
> 
> did it work?

no it didnt

**Comment by 9lag** [comment]
WAT DO U MEAN

**Comment by 9lag** [comment]
> > > > > > > > > > > im still working on a tutorial for installing it please wait
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > It works fine i can make a tutriol if u need lols its easy just like i tried changing the imageid to a image id like 9727038172039817 still didnt work but am i doing soemthing wrong
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > did you set it with the same app id as the one where rich presence assets are added?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Yes
> > > > > > > 
> > > > > > > 
> > > > > > > weird, I'll try checking it later since im adding a config file support atm
> > > > > > 
> > > > > > 
> > > > > > Do i need all the assets is that why like i didnt add small image
> > > > > 
> > > > > 
> > > > > what do you mean?
> > > > 
> > > > 
> > > > Like i didnt add small image
> > > 
> > > 
> > > i think so
> > 
> > 
> > Ok i tried same thing
> 
> did it work?

Idk how to use the image filename from the url w/out the extension instead of the key name

**Comment by kairusds** [comment]
@9lag the url of the asset image should be something like https://cdn.discordapp.com/app-assets/632447779013458728/655561063797872711.png 
just get the second 18 digit number from it without the file extension and set your appid to the same client id where the asset is
