### ISSUE TITLE
Your script is accurate and working.... 10/10. I'm currently hosting it on repl.it

### ISSUE THREAD

**Issue by 9lag** [kairusds/eidolonrp#5]
Your script is accurate and working.... 10/10. I'm currently hosting it on repl.it

_Originally posted by @Forgiving0 in https://github.com/kairusds/eidolonrp/issues/2#issuecomment-779974838_
how did you get it working????????/

**Comment by 9lag** [comment]
look at my other issue maybe u can help

**Comment by kairusds** [comment]
Refer to the new config please, I'll be posting the instructions on how to find the image ID sometime this day or tomorrow
