### ISSUE TITLE
Bad Licence Change

### ISSUE THREAD

**Issue by yellowsink** [kairusds/eidolonrp#6]
In commit 7328a6f0d33a9937d276e00571480e1190be841c you changed over from AGPL3 to MIT.  
As I noted [here](https://github.com/kairusds/eidolonrp/commit/7328a6f0d33a9937d276e00571480e1190be841c#commitcomment-47506688), the terms of the AGPL3 licence prevent that change.

**Comment by kairusds** [comment]
my bad i'll revert that change now thanks for the headsup

**Comment by yellowsink** [comment]
no problem 👍
