### ISSUE TITLE
It wont let me right click and when i get asset id it says unknown

### ISSUE THREAD

**Issue by 9lag** [kairusds/eidolonrp#8]

**Comment by kairusds** [comment]
are you on pc or mobile?

**Comment by 9lag** [comment]
> are you on pc or mobile?

sorry i got it now 
![image](https://user-images.githubusercontent.com/78369995/109177508-80ade800-774d-11eb-9dbd-bf75da74ad4d.png)

**Comment by kairusds** [comment]
alright
