### ISSUE TITLE
Works fine, not having any issues at all, but can be better.

### ISSUE THREAD

**Issue by thakuranuj24** [kairusds/eidolonrp#9]
The script is really very good and I'm not having any issues at all, but can you please add **Buttons** which redirect us to an url? It will be a great help if you do so cuz I've been trying to find a custom rich presence program with buttons which is a selfbot from days. Thanks.

**Comment by Hunter2807** [comment]
![image](https://user-images.githubusercontent.com/46440327/111636980-fffb7c80-881e-11eb-80df-bc7871f63d9f.png)
![image](https://user-images.githubusercontent.com/46440327/111636999-04c03080-881f-11eb-934f-c6a89c64b19d.png)
dude @thakuranuj24 see this :D. Don't use this. I have used discord.py, and its a code for selfbot. I myself, am a Python Coder and have coded in discord.py also haha

**Comment by vbajs** [comment]
> ![image](https://user-images.githubusercontent.com/46440327/111636980-fffb7c80-881e-11eb-80df-bc7871f63d9f.png)
> ![image](https://user-images.githubusercontent.com/46440327/111636999-04c03080-881f-11eb-934f-c6a89c64b19d.png)
> dude @thakuranuj24 see this :D. Don't use this. I have used discord.py, and its a code for selfbot. I myself, am a Python Coder and have coded in discord.py also haha

Yes, you are correct.
However, unlike the malicious nature of selfbots, this only creates a rich presence on your account. That's all it does.
It's also worth mentioning that it's ideal usage case is to get custom RPC on mobile (weither on Android or jailbroken iOS) or to have custom RPC without the discord cilent being running (unlike most custom RPC tools that require discord to be running, which is why they don't work on mobile)

**Comment by thakuranuj24** [comment]
Uhm, I asked about buttons and you guys started discussing about selfbots... ik this is a selfbot, I just wanted to know if buttons can also be used with it.

**Comment by vbajs** [comment]
> The script is really very good and I'm not having any issues at all, but can you please add **Buttons** which redirect us to an url? It will be a great help if you do so cuz I've been trying to find a custom rich presence program with buttons which is a selfbot from days. Thanks.

Unfortunately, discord.py doesn't have button support.
You could open a new issue over discord.py with the feature request tag for button support

**Comment by thakuranuj24** [comment]
I was asking about buttons and you guys started discussing about selfbots, I know it's a selfbot, and have no problem with it. I only wanna know if buttons can be added or not.

**Comment by thakuranuj24** [comment]
> > The script is really very good and I'm not having any issues at all, but can you please add **Buttons** which redirect us to an url? It will be a great help if you do so cuz I've been trying to find a custom rich presence program with buttons which is a selfbot from days. Thanks.
> 
> Unfortunately, discord.py doesn't have button support.
> You could open a new issue over discord.py with the feature request tag for button support

I will open a issue there, thanks for the help. :D
